language: node_js
node_js:
 - "stable"
cache:
 directories:
   - node_modules
script:
- npm run build || true
deploy:
  provider: heroku
  app: "portfolioallesjohns"
  api_key:
    secure: "41661bd5-d37e-4c59-9da7-aef0d5aa9cf4"